### ISSUE TITLE
Cant add new slides

### ISSUE THREAD

**Issue by Franpepper** [Contentify/Contentify#565]
Hi!

When I try to add a new slide, the error window appears.

here is the log file
I do not know what I'm doing wrong

> [2019-06-04 15:05:04] production.ERROR: ErrorException: preg_match(): Compilation failed: invalid range in character class at offset 1825 in /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php:1356
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'preg_match(): C...', '/home/laravel/p...', 1356, Array)
#1 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php(1356): preg_match('~^\n            ...', 'http://gamepals...')
#2 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(352): Illuminate\Validation\Validator->validateUrl('url', 'http://gamepals...', Array, Object(Illuminate\Validation\Validator))
#3 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(267): Illuminate\Validation\Validator->validateAttribute('url', 'Url')
#4 /home/laravel/public_html/vendor/watson/validating/src/ValidatingTrait.php(417): Illuminate\Validation\Validator->passes()
#5 /home/laravel/public_html/vendor/watson/validating/src/ValidatingTrait.php(270): Contentify\Models\BaseModel->performValidation(Array)
#6 /home/laravel/public_html/vendor/watson/validating/src/ValidatingObserver.php(51): Contentify\Models\BaseModel->isValid()
#7 /home/laravel/public_html/vendor/watson/validating/src/ValidatingObserver.php(20): Watson\Validating\ValidatingObserver->performValidation(Object(App\Modules\Slides\Slide), 'saving')
#8 [internal function]: Watson\Validating\ValidatingObserver->saving(Object(App\Modules\Slides\Slide))
#9 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(367): call_user_func_array(Array, Array)
#10 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.saving...', Array)
#11 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(159): Illuminate\Events\Dispatcher->dispatch('eloquent.saving...', Array, true)
#12 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(148): Illuminate\Events\Dispatcher->until('eloquent.saving...', Object(App\Modules\Slides\Slide))
#13 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(506): Illuminate\Database\Eloquent\Model->fireModelEvent('saving')
#14 /home/laravel/public_html/contentify/ModelHandler.php(395): Illuminate\Database\Eloquent\Model->save()
#15 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Contentify\ModelHandler->store()
#16 /home/laravel/public_html/contentify/Traits/ModelHandlerTrait.php(31): Illuminate\Support\Facades\Facade::__callStatic('store', Array)
#17 [internal function]: App\Modules\Slides\Http\Controllers\AdminSlidesController->store()
#18 /home/laravel/public_html/contentify/Controllers/BaseController.php(114): call_user_func_array(Array, Array)
#19 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Contentify\Controllers\BaseController->callAction('store', Array)
#20 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Modules\Slides\Http\Controllers\AdminSlidesController), 'store')
#21 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#22 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#23 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /home/laravel/public_html/app/Http/Middleware/VerifyAdminAccess.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\VerifyAdminAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home/laravel/public_html/contentify/Middleware/UpdateUser.php(114): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Contentify\Middleware\UpdateUser->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/laravel/public_html/app/Http/Middleware/VerifyCsrfToken.php(52): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /home/laravel/public_html/contentify/Middleware/HttpsRedirect.php(33): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Contentify\Middleware\HttpsRedirect->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#54 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#56 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 /home/laravel/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#69 /home/laravel/public_html/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#70 {main}  `

**Comment by Franpepper** [comment]
I fixed it, the problem was the php version.

The version was php-fpm7.3, I changed it to php-fpm7.2 and it worked correctly.
