### ISSUE TITLE
News: Type error (NewsController.php on line 159)

### ISSUE THREAD

**Issue by renegade1337** [Contentify/Contentify#613]
**Meine Arbeitsumgebung:**
Contentify v3.0
Windows 10
XAMPP 7.4.3
PHP 7.4.3
MariaDB 10.4.11
Apache 2.4.41

Wenn ich in meiner Arbeitsumgebung im Frontend auf eine News klicke erhalte ich folgenden Type error:

```
Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Type error: Argument 1 passed to Contentify\Controllers\BaseController::openGraph() must be an instance of OpenGraph, instance of ChrisKonnertz\OpenGraph\OpenGraph given, called in C:\xampp\htdocs\root\Contentify\app\Modules\News\Http\Controllers\NewsController.php on line 159"

Stacktrace:
#58 Symfony\Component\Debug\Exception\FatalThrowableError in C:\xampp\htdocs\root\Contentify\contentify\Controllers\BaseController.php:372
#57 Contentify\Controllers\BaseController:openGraph in C:\xampp\htdocs\root\Contentify\app\Modules\News\Http\Controllers\NewsController.php:159
#56 App\Modules\News\Http\Controllers\NewsController:show in C:\xampp\htdocs\root\Contentify\contentify\Controllers\BaseController.php:108
#55 call_user_func_array in C:\xampp\htdocs\root\Contentify\contentify\Controllers\BaseController.php:108
#54 Contentify\Controllers\BaseController:callAction in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
#53 Illuminate\Routing\ControllerDispatcher:dispatch in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Route.php:212
#52 Illuminate\Routing\Route:runController in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Route.php:169
#51 Illuminate\Routing\Route:run in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Router.php:658
#50 Illuminate\Routing\Router:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\app\Http\Middleware\VerifyAdminAccess.php:40
#48 App\Http\Middleware\VerifyAdminAccess:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\contentify\Middleware\UpdateUser.php:114
#45 Contentify\Middleware\UpdateUser:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#42 Illuminate\Routing\Middleware\SubstituteBindings:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\app\Http\Middleware\VerifyCsrfToken.php:24
#39 App\Http\Middleware\VerifyCsrfToken:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
#33 Illuminate\Session\Middleware\StartSession:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:66
#27 Illuminate\Cookie\Middleware\EncryptCookies:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\contentify\Middleware\HttpsRedirect.php:33
#24 Contentify\Middleware\HttpsRedirect:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#23 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#22 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#21 Illuminate\Pipeline\Pipeline:then in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Router.php:660
#20 Illuminate\Routing\Router:runRouteWithinStack in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Router.php:635
#19 Illuminate\Routing\Router:runRoute in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Router.php:601
#18 Illuminate\Routing\Router:dispatchToRoute in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Router.php:590
#17 Illuminate\Routing\Router:dispatch in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
#16 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\fideloper\proxy\src\TrustProxies.php:56
#14 Fideloper\Proxy\TrustProxies:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in C:\xampp\htdocs\root\Contentify\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in C:\xampp\htdocs\root\Contentify\public\index.php:55
```

**Comment by chriskonnertz** [comment]
Hallo @renegade1337 

Hatte sich das irgendwie lösen lassen?

**Comment by renegade1337** [comment]
Leider nein

**Comment by Trickfilm400** [comment]
Selber Fehler hier auch, mit versch. PHP versionen

```
[2020-07-19 01:08:18] local.ERROR: Type error: Argument 1 passed to Contentify\Controllers\BaseController::openGraph() must be an instance of OpenGraph, instance of ChrisKonnertz\OpenGraph\OpenGraph given, called in <www-path>/app/Modules/News/Http/Controllers/NewsController.php on line 159 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Contentify\\Controllers\\BaseController::openGraph() must be an instance of OpenGraph, instance of ChrisKonnertz\\OpenGraph\\OpenGraph given, called in <www-path>/app/Modules/News/Http/Controllers/NewsController.php on line 159 at <www-path>/contentify/Controllers/BaseController.php:372)
[stacktrace]
#0 <www-path>/app/Modules/News/Http/Controllers/NewsController.php(159): Contentify\\Controllers\\BaseController->openGraph(Object(ChrisKonnertz\\OpenGraph\\OpenGraph))
#1 [internal function]: App\\Modules\\News\\Http\\Controllers\\NewsController->show(1, 'test')
#2 <www-path>/contentify/Controllers/BaseController.php(108): call_user_func_array(Array, Array)
#3 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Contentify\\Controllers\\BaseController->callAction('show', Array)
#4 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Modules\\News\\Http\\Controllers\\NewsController), 'show')
#5 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#6 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#7 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 <www-path>/app/Http/Middleware/VerifyAdminAccess.php(40): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\VerifyAdminAccess->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#10 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 <www-path>/contentify/Middleware/UpdateUser.php(114): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Contentify\\Middleware\\UpdateUser->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 <www-path>/app/Http/Middleware/VerifyCsrfToken.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 <www-path>/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 <www-path>/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 <www-path>/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 <www-path>/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 <www-path>/contentify/Middleware/HttpsRedirect.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Contentify\\Middleware\\HttpsRedirect->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#38 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#39 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#40 <www-path>/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#41 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#42 <www-path>/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 <www-path>/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 <www-path>/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 <www-path>/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 <www-path>/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 <www-path>/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 <www-path>/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#56 <www-path>/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#57 <www-path>/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#58 {main}
"} 

```

**Comment by kamohy** [comment]
This exact type mismatch is already corrected in the later upstream 3.2-dev branch by Chris in commit 7e0294ec1d54a76715fa08e910eb1b32bd064537: BaseController now imports ChrisKonnertz\\OpenGraph\\OpenGraph instead of resolving the facade alias as a parameter type. The unofficial Bad Hippo community fork includes that upstream correction: https://github.com/Bad-Hippo-com/Contentify . Its current stabilization baseline is still PHP 7.4 and Laravel 6.20.30; we are testing existing workflows before upgrading the stack. We will separately record the end-to-end news test in our upstream triage.
